
var ronchModule = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(ronchModule) {
  ronchModule = ronchModule || {};

var b;b||(b=typeof ronchModule !== 'undefined' ? ronchModule : {});var h={},l;for(l in b)b.hasOwnProperty(l)&&(h[l]=b[l]);var m=!1,q=!1,r=!1,aa=!1,t=!1;m="object"===typeof window;q="function"===typeof importScripts;r=(aa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!m&&!q;t=!m&&!r&&!q;var u="",v,w;
if(r){u=__dirname+"/";var x,y;v=function(a,c){x||(x=require("fs"));y||(y=require("path"));a=y.normalize(a);a=x.readFileSync(a);return c?a:a.toString()};w=function(a){a=v(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",A);b.inspect=function(){return"[Emscripten Module object]"}}else if(t)"undefined"!=typeof read&&(v=function(a){return read(a)}),
w=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(m||q)q?u=self.location.href:document.currentScript&&(u=document.currentScript.src),_scriptDir&&(u=_scriptDir),0!==u.indexOf("blob:")?u=u.substr(0,u.lastIndexOf("/")+1):u="",v=function(a){var c=
new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},q&&(w=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)});var B=b.print||console.log.bind(console),C=b.printErr||console.warn.bind(console);for(l in h)h.hasOwnProperty(l)&&(b[l]=h[l]);h=null;var ba={"f64-rem":function(a,c){return a%c},"debugger":function(){}},D;b.wasmBinary&&(D=b.wasmBinary);"object"!==typeof WebAssembly&&C("no native wasm support detected");
var E,F=!1;function assert(a,c){a||A("Assertion failed: "+c)}function ca(a){var c=b["_"+a];assert(c,"Cannot call unknown function "+a+", make sure it is exported");return c}var G="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function H(a,c,d){var f=c+d;for(d=c;a[d]&&!(d>=f);)++d;if(16<d-c&&a.subarray&&G)return G.decode(a.subarray(c,d));for(f="";c<d;){var e=a[c++];if(e&128){var n=a[c++]&63;if(192==(e&224))f+=String.fromCharCode((e&31)<<6|n);else{var p=a[c++]&63;e=224==(e&240)?(e&15)<<12|n<<6|p:(e&7)<<18|n<<12|p<<6|a[c++]&63;65536>e?f+=String.fromCharCode(e):(e-=65536,f+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else f+=String.fromCharCode(e)}return f}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");
var buffer,I,J,K,L=b.TOTAL_MEMORY||16777216;b.wasmMemory?E=b.wasmMemory:E=new WebAssembly.Memory({initial:L/65536,maximum:L/65536});E&&(buffer=E.buffer);L=buffer.byteLength;var M=buffer;buffer=M;b.HEAP8=I=new Int8Array(M);b.HEAP16=new Int16Array(M);b.HEAP32=K=new Int32Array(M);b.HEAPU8=J=new Uint8Array(M);b.HEAPU16=new Uint16Array(M);b.HEAPU32=new Uint32Array(M);b.HEAPF32=new Float32Array(M);b.HEAPF64=new Float64Array(M);K[3780]=5258032;
function N(a){for(;0<a.length;){var c=a.shift();if("function"==typeof c)c();else{var d=c.F;"number"===typeof d?void 0===c.A?b.dynCall_v(d):b.dynCall_vi(d,c.A):d(void 0===c.A?null:c.A)}}}var O=[],da=[],ea=[],P=[];function fa(){var a=b.preRun.shift();O.unshift(a)}var Q=0,T=null,U=null;b.preloadedImages={};b.preloadedAudios={};function ha(){var a=V;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var V="index.wasm";
if(!ha()){var ia=V;V=b.locateFile?b.locateFile(ia,u):u+ia}function ja(){try{if(D)return new Uint8Array(D);if(w)return w(V);throw"both async and sync fetching of the wasm failed";}catch(a){A(a)}}function ka(){return D||!m&&!q||"function"!==typeof fetch?new Promise(function(a){a(ja())}):fetch(V,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+V+"'";return a.arrayBuffer()}).catch(function(){return ja()})}
function la(a){function c(a){b.asm=a.exports;Q--;b.monitorRunDependencies&&b.monitorRunDependencies(Q);0==Q&&(null!==T&&(clearInterval(T),T=null),U&&(a=U,U=null,a()))}function d(a){c(a.instance)}function f(a){return ka().then(function(a){return WebAssembly.instantiate(a,e)}).then(a,function(a){C("failed to asynchronously prepare wasm: "+a);A(a)})}var e={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:ba};Q++;b.monitorRunDependencies&&b.monitorRunDependencies(Q);if(b.instantiateWasm)try{return b.instantiateWasm(e,
c)}catch(n){return C("Module.instantiateWasm callback failed with error: "+n),!1}(function(){if(D||"function"!==typeof WebAssembly.instantiateStreaming||ha()||"function"!==typeof fetch)return f(d);fetch(V,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,e).then(d,function(a){C("wasm streaming compile failed: "+a);C("falling back to ArrayBuffer instantiation");f(d)})})})();return{}}
b.asm=function(a,c){c.memory=E;c.table=new WebAssembly.Table({initial:314,maximum:314,element:"anyfunc"});c.__memory_base=1024;c.__table_base=0;return la(c)};var ma=[null,[],[]],W=0;function X(){W+=4;return K[W-4>>2]}var na={};function oa(){A("OOM")}
var pa=b.asm({},{b:A,n:function(){F=!0;throw"Pure virtual function called!";},d:function(a){b.___errno_location&&(K[b.___errno_location()>>2]=a);return a},i:function(a,c){W=c;try{return na.D(),X(),X(),X(),X(),0}catch(d){return"undefined"!==typeof FS&&d instanceof FS.B||A(d),-d.C}},c:function(a,c){W=c;try{var d=X(),f=X(),e=X();for(c=a=0;c<e;c++){for(var n=K[f+8*c>>2],p=K[f+(8*c+4)>>2],k=0;k<p;k++){var z=J[n+k],R=ma[d];0===z||10===z?((1===d?B:C)(H(R,0)),R.length=0):R.push(z)}a+=p}return a}catch(S){return"undefined"!==
typeof FS&&S instanceof FS.B||A(S),-S.C}},h:function(a,c){W=c;try{return na.D(),0}catch(d){return"undefined"!==typeof FS&&d instanceof FS.B||A(d),-d.C}},g:function(){b.abort()},f:function(){return I.length},e:function(a,c,d){J.set(J.subarray(c,c+d),a)},m:function(a){oa(a)},l:function(){A("trap!")},k:function(a){var c=Date.now()/1E3|0;a&&(K[a>>2]=c);return c},j:oa,a:15120},buffer);b.asm=pa;b.___errno_location=function(){return b.asm.o.apply(null,arguments)};
b._calcRonch=function(){return b.asm.p.apply(null,arguments)};b._free=function(){return b.asm.q.apply(null,arguments)};b._malloc=function(){return b.asm.r.apply(null,arguments)};var qa=b.stackAlloc=function(){return b.asm.u.apply(null,arguments)},ra=b.stackRestore=function(){return b.asm.v.apply(null,arguments)},sa=b.stackSave=function(){return b.asm.w.apply(null,arguments)};b.dynCall_v=function(){return b.asm.s.apply(null,arguments)};b.dynCall_vi=function(){return b.asm.t.apply(null,arguments)};
b.asm=pa;
b.ccall=function(a,c,d,f){var e={string:function(a){var c=0;if(null!==a&&void 0!==a&&0!==a){var d=(a.length<<2)+1;c=qa(d);var e=c;if(0<d){d=e+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(e>=d)break;J[e++]=g}else{if(2047>=g){if(e+1>=d)break;J[e++]=192|g>>6}else{if(65535>=g){if(e+2>=d)break;J[e++]=224|g>>12}else{if(e+3>=d)break;J[e++]=240|g>>18;J[e++]=128|g>>12&63}J[e++]=128|g>>6&63}J[e++]=128|g&63}}J[e]=
0}}return c},array:function(a){var c=qa(a.length);I.set(a,c);return c}},n=ca(a),p=[];a=0;if(f)for(var k=0;k<f.length;k++){var z=e[d[k]];z?(0===a&&(a=sa()),p[k]=z(f[k])):p[k]=f[k]}d=n.apply(null,p);d=function(a){return"string"===c?a?H(J,a,void 0):"":"boolean"===c?!!a:a}(d);0!==a&&ra(a);return d};var Y;b.then=function(a){if(Y)a(b);else{var c=b.onRuntimeInitialized;b.onRuntimeInitialized=function(){c&&c();a(b)}}return b};U=function ta(){Y||Z();Y||(U=ta)};
function Z(){function a(){if(!Y&&(Y=!0,!F)){N(da);N(ea);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var a=b.postRun.shift();P.unshift(a)}N(P)}}if(!(0<Q)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)fa();N(O);0<Q||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},1);a()},1)):a())}}b.run=Z;
function A(a){if(b.onAbort)b.onAbort(a);B(a);C(a);F=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}b.abort=A;if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();Z();


  return ronchModule
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = ronchModule;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return ronchModule; });
    else if (typeof exports === 'object')
      exports["ronchModule"] = ronchModule;
    