
var ronchModule = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(ronchModule) {
  ronchModule = ronchModule || {};

var b;b||(b=typeof ronchModule !== 'undefined' ? ronchModule : {});var h={},k;for(k in b)b.hasOwnProperty(k)&&(h[k]=b[k]);var n=!1,p=!1,r=!1,aa=!1,t=!1;n="object"===typeof window;p="function"===typeof importScripts;r=(aa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!n&&!p;t=!n&&!r&&!p;var u="",v,w;
if(r){u=__dirname+"/";var x,z;v=function(a,c){x||(x=require("fs"));z||(z=require("path"));a=z.normalize(a);a=x.readFileSync(a);return c?a:a.toString()};w=function(a){a=v(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",A);b.inspect=function(){return"[Emscripten Module object]"}}else if(t)"undefined"!=typeof read&&(v=function(a){return read(a)}),
w=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(n||p)p?u=self.location.href:document.currentScript&&(u=document.currentScript.src),_scriptDir&&(u=_scriptDir),0!==u.indexOf("blob:")?u=u.substr(0,u.lastIndexOf("/")+1):u="",v=function(a){var c=
new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},p&&(w=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)});var B=b.print||console.log.bind(console),C=b.printErr||console.warn.bind(console);for(k in h)h.hasOwnProperty(k)&&(b[k]=h[k]);h=null;var D;b.wasmBinary&&(D=b.wasmBinary);"object"!==typeof WebAssembly&&C("no native wasm support detected");
var E,ba=new WebAssembly.Table({initial:200,maximum:200,element:"anyfunc"}),G=!1;function assert(a,c){a||A("Assertion failed: "+c)}function ca(a){var c=b["_"+a];assert(c,"Cannot call unknown function "+a+", make sure it is exported");return c}var H="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function I(a,c,d){var f=c+d;for(d=c;a[d]&&!(d>=f);)++d;if(16<d-c&&a.subarray&&H)return H.decode(a.subarray(c,d));for(f="";c<d;){var e=a[c++];if(e&128){var l=a[c++]&63;if(192==(e&224))f+=String.fromCharCode((e&31)<<6|l);else{var q=a[c++]&63;e=224==(e&240)?(e&15)<<12|l<<6|q:(e&7)<<18|l<<12|q<<6|a[c++]&63;65536>e?f+=String.fromCharCode(e):(e-=65536,f+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else f+=String.fromCharCode(e)}return f}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");
var buffer,J,K,L,M=b.TOTAL_MEMORY||16777216;b.wasmMemory?E=b.wasmMemory:E=new WebAssembly.Memory({initial:M/65536,maximum:M/65536});E&&(buffer=E.buffer);M=buffer.byteLength;var N=buffer;buffer=N;b.HEAP8=J=new Int8Array(N);b.HEAP16=new Int16Array(N);b.HEAP32=L=new Int32Array(N);b.HEAPU8=K=new Uint8Array(N);b.HEAPU16=new Uint16Array(N);b.HEAPU32=new Uint32Array(N);b.HEAPF32=new Float32Array(N);b.HEAPF64=new Float64Array(N);L[4088]=5259392;
function Q(a){for(;0<a.length;){var c=a.shift();if("function"==typeof c)c();else{var d=c.u;"number"===typeof d?void 0===c.s?b.dynCall_v(d):b.dynCall_vi(d,c.s):d(void 0===c.s?null:c.s)}}}var R=[],S=[],da=[],T=[];function ea(){var a=b.preRun.shift();R.unshift(a)}var U=0,V=null,W=null;b.preloadedImages={};b.preloadedAudios={};function A(a){if(b.onAbort)b.onAbort(a);B(a);C(a);G=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}
function fa(){var a=X;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var X="index.wasm";if(!fa()){var ha=X;X=b.locateFile?b.locateFile(ha,u):u+ha}function ia(){try{if(D)return new Uint8Array(D);if(w)return w(X);throw"both async and sync fetching of the wasm failed";}catch(a){A(a)}}
function ja(){return D||!n&&!p||"function"!==typeof fetch?new Promise(function(a){a(ia())}):fetch(X,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+X+"'";return a.arrayBuffer()}).catch(function(){return ia()})}S.push({u:function(){ka()}});
var la=[null,[],[]],ma={d:function(){A()},b:function(a,c,d){K.set(K.subarray(c,c+d),a)},c:function(){A("OOM")},e:function(){return 0},a:function(){return 0},f:function(a,c,d,f){try{for(var e=0,l=0;l<d;l++){for(var q=L[c+8*l>>2],m=L[c+(8*l+4)>>2],y=0;y<m;y++){var F=K[q+y],O=la[a];0===F||10===F?((1===a?B:C)(I(O,0)),O.length=0):O.push(F)}e+=m}L[f>>2]=e;return 0}catch(P){return"undefined"!==typeof FS&&P instanceof FS.v||A(P),P.w}},memory:E,table:ba,g:function(a){var c=Date.now()/1E3|0;a&&(L[a>>2]=c);
return c}},na=function(){function a(a){b.asm=a.exports;U--;b.monitorRunDependencies&&b.monitorRunDependencies(U);0==U&&(null!==V&&(clearInterval(V),V=null),W&&(a=W,W=null,a()))}function c(c){a(c.instance)}function d(a){return ja().then(function(a){return WebAssembly.instantiate(a,f)}).then(a,function(a){C("failed to asynchronously prepare wasm: "+a);A(a)})}var f={env:ma,wasi_unstable:ma};U++;b.monitorRunDependencies&&b.monitorRunDependencies(U);if(b.instantiateWasm)try{return b.instantiateWasm(f,
a)}catch(e){return C("Module.instantiateWasm callback failed with error: "+e),!1}(function(){if(D||"function"!==typeof WebAssembly.instantiateStreaming||fa()||"function"!==typeof fetch)return d(c);fetch(X,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,f).then(c,function(a){C("wasm streaming compile failed: "+a);C("falling back to ArrayBuffer instantiation");d(c)})})})();return{}}();b.asm=na;var ka=b.___wasm_call_ctors=function(){return b.asm.h.apply(null,arguments)};
b._calcRonch=function(){return b.asm.i.apply(null,arguments)};b._malloc=function(){return b.asm.j.apply(null,arguments)};b._free=function(){return b.asm.k.apply(null,arguments)};var oa=b.stackSave=function(){return b.asm.l.apply(null,arguments)},pa=b.stackAlloc=function(){return b.asm.m.apply(null,arguments)},qa=b.stackRestore=function(){return b.asm.n.apply(null,arguments)};b.dynCall_v=function(){return b.asm.o.apply(null,arguments)};b.dynCall_vi=function(){return b.asm.p.apply(null,arguments)};
b.asm=na;
b.ccall=function(a,c,d,f){var e={string:function(a){var c=0;if(null!==a&&void 0!==a&&0!==a){var d=(a.length<<2)+1;c=pa(d);var e=c;if(0<d){d=e+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var F=a.charCodeAt(++f);g=65536+((g&1023)<<10)|F&1023}if(127>=g){if(e>=d)break;K[e++]=g}else{if(2047>=g){if(e+1>=d)break;K[e++]=192|g>>6}else{if(65535>=g){if(e+2>=d)break;K[e++]=224|g>>12}else{if(e+3>=d)break;K[e++]=240|g>>18;K[e++]=128|g>>12&63}K[e++]=128|g>>6&63}K[e++]=128|g&63}}K[e]=
0}}return c},array:function(a){var c=pa(a.length);J.set(a,c);return c}},l=ca(a),q=[];a=0;if(f)for(var m=0;m<f.length;m++){var y=e[d[m]];y?(0===a&&(a=oa()),q[m]=y(f[m])):q[m]=f[m]}d=l.apply(null,q);d=function(a){return"string"===c?a?I(K,a,void 0):"":"boolean"===c?!!a:a}(d);0!==a&&qa(a);return d};var Y;b.then=function(a){if(Y)a(b);else{var c=b.onRuntimeInitialized;b.onRuntimeInitialized=function(){c&&c();a(b)}}return b};W=function ra(){Y||Z();Y||(W=ra)};
function Z(){function a(){if(!Y&&(Y=!0,!G)){Q(S);Q(da);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var a=b.postRun.shift();T.unshift(a)}Q(T)}}if(!(0<U)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)ea();Q(R);0<U||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},1);a()},1)):a())}}b.run=Z;
if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();Z();


  return ronchModule
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = ronchModule;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return ronchModule; });
    else if (typeof exports === 'object')
      exports["ronchModule"] = ronchModule;
    